// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGjKSNFl_0J8dTB-mShmjSwnhrip6DPi0',
    appId: '1:100695326162:web:070aa421f4b6a5e5fb5c0b',
    messagingSenderId: '100695326162',
    projectId: 'flutterfirebase-5cb18',
    authDomain: 'flutterfirebase-5cb18.firebaseapp.com',
    storageBucket: 'flutterfirebase-5cb18.appspot.com',
    measurementId: 'G-43DK3BJ92F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpvu3rTXFThVXzAT_BUTA29BiwhXQYbhI',
    appId: '1:100695326162:android:48f1c833c042f3d9fb5c0b',
    messagingSenderId: '100695326162',
    projectId: 'flutterfirebase-5cb18',
    storageBucket: 'flutterfirebase-5cb18.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBir8MG_gR48PQFmaYCGUsgtrTQK1Cpeh4',
    appId: '1:100695326162:ios:5b3591bd8166dd33fb5c0b',
    messagingSenderId: '100695326162',
    projectId: 'flutterfirebase-5cb18',
    storageBucket: 'flutterfirebase-5cb18.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBir8MG_gR48PQFmaYCGUsgtrTQK1Cpeh4',
    appId: '1:100695326162:ios:5b3591bd8166dd33fb5c0b',
    messagingSenderId: '100695326162',
    projectId: 'flutterfirebase-5cb18',
    storageBucket: 'flutterfirebase-5cb18.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGjKSNFl_0J8dTB-mShmjSwnhrip6DPi0',
    appId: '1:100695326162:web:6497df323c47a5cffb5c0b',
    messagingSenderId: '100695326162',
    projectId: 'flutterfirebase-5cb18',
    authDomain: 'flutterfirebase-5cb18.firebaseapp.com',
    storageBucket: 'flutterfirebase-5cb18.appspot.com',
    measurementId: 'G-C3FNTYVP4Y',
  );
}
